### ISSUE TITLE
CloudWatch Log Group does not get created automatically with CloudFormation Template

### ISSUE THREAD

**Issue by vladraul86** [zoph-io/aws-security-survival-kit#1]
Hi,

The CTLogGroupName variable needs to point to an already existing Log Group created in CloudWatch. If the log group is not created the following errors are reported in CloudFormation: 
![cloudformation_error](https://user-images.githubusercontent.com/114870246/193462217-3113987b-4875-47c9-9922-d19f1378a9fd.JPG)

If the log group is created, the kit works like a charm!
Can you add in the cloud formation template also the log group creation? I recommend to put 1 week retention not to have surprise costs, or have the retention defined as a variable in your Makefile.

Thanks for the work!

**Comment by z0ph** [comment]
Hi @vladraul86,

This is correct. You will need to have an existing CloudTrail CloudWatch LogGroup before deploying this kit, and you will need to fill this parameter in the Makefile.

As you can only have one CloudWatch LogGroup associated with your CloudTrail setup, and as a lot of folks has already this setup in place, I've decided to assume that this is an existing LogGroup in your account. Handling this LogGroup creation is a bit difficult as I will need to check if there is an existing LogGroup. This is not something easy with only CloudFormation and Makefile.

It's cool that you have successfully deployed my kit ;)

Thanks for this feedback. I've updated the doc with more details on parameters.
