### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by StevenSmiley** [zoph-io/aws-security-survival-kit#11]
Please consider defining a license, I would like to use this in line with your wishes. Thanks.

**Comment by z0ph** [comment]
@StevenSmiley What do you have in mind regarding the usage of ASSK? Any plan to add more features or supported alerting?

**Comment by StevenSmiley** [comment]
I have found ASSK useful to recommend to my customers as a starting point if they have no alerting in place and aren't planning to deploy a more robust system.

I'd be happy to add more alerts if you'd like.

**Comment by z0ph** [comment]
Great @StevenSmiley, thanks for letting me know. Happy to review any PR on new alerting. Thanks for your contribution to this OSS.
