### ISSUE TITLE
Ideas for later

### ISSUE THREAD

**Issue by z0ph** [zoph-io/aws-security-survival-kit#14]
- Better naming of assets with a assk prefix everywhere #18 
- Feature flag / cherry-pick of alerting
- Better Dashboarding Capabilities (Observability)
- Full Integration with AWS ChatBot (Teams + Slack)
- New detections based [on this paper](https://securitylabs.datadoghq.com/articles/following-attackers-trail-in-aws-methodology-findings-in-the-wild/)

**Comment by z0ph** [comment]
https://aws.amazon.com/blogs/aws/new-block-public-sharing-of-amazon-ebs-snapshots/

**Comment by z0ph** [comment]
> https://aws.amazon.com/blogs/aws/new-block-public-sharing-of-amazon-ebs-snapshots/

Done.

**Comment by z0ph** [comment]
Its already the case with `deploy` if there is existing stack with the same name, it will try to generate the changeset and update the existing stack without creating a brand new one.

Do you see a different behaviour?

**Comment by christophelimpalair** [comment]
Hey no you're right, this is probably unneeded since the command can do both. I was thinking more in terms of making it beginner friendly since there are no mentions of "how to update" in the readme, and it might stump someone who's knew to CloudFormation, but that could be solved with an update to the readme instead of adding another command and probably overkill...so ignore me :)

**Comment by christophelimpalair** [comment]
I haven't gone through this list yet but this looks like it has some good actions we may want to include. Posting here so we can sift through at some point: https://github.com/4n6ir/expediate

**Comment by z0ph** [comment]
> I haven't gone through this list yet but this looks like it has some good actions we may want to include. Posting here so we can sift through at some point: https://github.com/4n6ir/expediate

Sounds awesome, thanks for sharing Christophe!

**Comment by z0ph** [comment]
Closed I've create an issue for each one, easier to follow.
