### ISSUE TITLE
Better naming of assets with a assk prefix everywhere

### ISSUE THREAD

**Issue by christophelimpalair** [zoph-io/aws-security-survival-kit#18]
From "Ideas for later" #14 

I'll grab this one @z0ph and separating so we can tie PR to issue without closing the ideas list

**Comment by z0ph** [comment]
Great, thanks!

**Comment by christophelimpalair** [comment]
I've got a PR for this one coming up in a minute. I think I got it all but please double check :). For the CloudWatch alarms, I added the prefix after the name of the alarm unlike with eventbridge rules, because I figured it would be cleaner for email subject lines. LMK if you disagree and I can swap it
