### ISSUE TITLE
N00b question: How to find the actual "Unauthorized API Call" that triggered the alarm

### ISSUE THREAD

**Issue by peterflat** [zoph-io/aws-security-survival-kit#6]
I am not the best at navigating CloudTrail, but I am usually able to find things. However, after installing this excellent set of cloudfront scripts, I am getting notifications every so often that there is an unauthorized api call and I can't find them. Any assistance? Thank you again for creating this kit.

**Comment by z0ph** [comment]
Hey @peterflat,

There is no n00b question.

You can get more information about access denied on your account by using CloudWatch Insights.

Using this query on the LogGroup of CloudTrail.

```sql
fields eventTime, eventName, eventSource, userIdentity.sessionContext.sessionIssuer.userName as Principal, userIdentity.invokedBy as InvokedBy, errorCode

 | filter errorCode like /(Client.UnauthorizedOperation|AccessDenied)/
```

**Comment by peterflat** [comment]
Thank you so much for the quick response! 🙏

**Comment by z0ph** [comment]
I've added a new dashboard, it will be easier to follow what is ringing on your account 🔔 

![CleanShot 2022-11-15 at 16 30 33@2x](https://user-images.githubusercontent.com/20846187/201961569-00b6f45c-3a15-4f98-97af-dece3dc8f562.png)
